name=FSRReader
version=1.0.0
author=LAVANA
maintainer=LAVANA
sentence=Librería para leer sensores FSR de presión con ESP32.
paragraph=Lectura de sensores de fuerza FSR con filtro de atenuación, ideal para control de velocidad o dinámica en sistemas musicales. Optimizado para ESP32.
category=Sensors
architectures=esp32
