name=SoftPotReader
version=1.0.0
author=LAVANA
maintainer=LAVANA
sentence=Librería para leer sensores SoftPot de posición con ESP32.
paragraph=Lectura de sensores tipo SoftPot (posición lineal resistiva) para proyectos de control musical. Incluye filtro de atenuación y mínima lectura múltiple para mejorar estabilidad.
category=Sensors
architectures=esp32
